spring.datasource:
  url: jdbc:h2:mem:weolbu;MODE=MySQL;
  driver-class-name: org.h2.Driver
  username: sa
  password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
